# Generated by Django 4.1.6 on 2023-02-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='management.skill'),
        ),
    ]
