# Generated by Django 4.1.6 on 2023-02-04 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_volunteer_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.organization'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.ManyToManyField(blank=True, to='management.skill'),
        ),
    ]
