# Generated by Django 4.1.6 on 2023-02-04 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_volunteer_organization_alter_volunteer_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='id',
        ),
        migrations.AddField(
            model_name='resource',
            name='resourceID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
