# Generated by Django 4.1.6 on 2023-02-04 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_resource_id_resource_resourceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.organization'),
            preserve_default=False,
        ),
    ]
