# Generated by Django 4.1.6 on 2023-02-04 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('reporting', '0002_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('severity', models.IntegerField()),
                ('location_lat', models.FloatField()),
                ('location_lon', models.FloatField()),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.volunteer')),
            ],
            options={
                'unique_together': {('name', 'description')},
            },
        ),
    ]
