# Generated by Django 4.1.6 on 2023-02-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateTimeField(auto_created=True, editable=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_lon',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
