# Generated by Django 4.1.6 on 2023-02-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_alter_report_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='location_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='location_lon',
            new_name='lon',
        ),
    ]
